export default {
  ADMIN: {
    CREATE_USER: 'CREATE_USER',
    LIST_USER_BY_ID: 'LIST_USER_BY_ID',
    LIST_USER: 'LIST_USER',
    CREATE_ROLE: 'CREATE_ROLE',
    LIST_ROLE: 'LIST_ROLE',
    LIST_ROLE_PERMISSION: 'LIST_ROLE_PERMISSION',
    CREATE_ROLE_PERMISSION: 'CREATE_ROLE_PERMISSION',
    ADD_PERMISSION_TO_USER: 'ADD_PERMISSION_TO_USER',
    REMOVE_PERMISSION_TO_USER: 'REMOVE_PERMISSION_TO_USER',
  },
  SUPPORT_TEAM: {},
};
